#!/usr/bin/env python
"""
Script لإنشاء جدول accounts_user في public schema يدوياً
"""
import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'tenants.aqua_core.settings')
django.setup()

from django.db import connection
from django_tenants.utils import get_public_schema_name

# الانتقال إلى public schema
public_schema = get_public_schema_name()
connection.set_schema_to_public()

print(f'🔍 Schema الحالي: {connection.schema_name}')

# SQL لإنشاء الجدول
sql = """
CREATE TABLE IF NOT EXISTS "accounts_user" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "password" varchar(128) NOT NULL,
    "last_login" timestamp with time zone NULL,
    "is_superuser" boolean NOT NULL,
    "username" varchar(150) NOT NULL UNIQUE,
    "first_name" varchar(150) NOT NULL,
    "last_name" varchar(150) NOT NULL,
    "email" varchar(254) NOT NULL,
    "is_staff" boolean NOT NULL,
    "date_joined" timestamp with time zone NOT NULL,
    "full_name" varchar(255) NOT NULL,
    "phone" varchar(20) NULL,
    "role" varchar(20) NOT NULL,
    "is_active" boolean NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "accounts_user_groups" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "group_id" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "accounts_user_user_permissions" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "permission_id" integer NOT NULL
);

CREATE INDEX IF NOT EXISTS "accounts_user_username_6088629e_like" ON "accounts_user" ("username" varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS "accounts_us_usernam_c0ea66_idx" ON "accounts_user" ("username");
CREATE INDEX IF NOT EXISTS "accounts_us_email_74c8d6_idx" ON "accounts_user" ("email");
CREATE INDEX IF NOT EXISTS "accounts_us_role_1fa9a5_idx" ON "accounts_user" ("role");
CREATE INDEX IF NOT EXISTS "accounts_us_is_acti_a5841d_idx" ON "accounts_user" ("is_active");

DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'accounts_user_groups_user_id_group_id_59c0b32f_uniq'
    ) THEN
        ALTER TABLE "accounts_user_groups" 
            ADD CONSTRAINT "accounts_user_groups_user_id_group_id_59c0b32f_uniq" UNIQUE ("user_id", "group_id");
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'accounts_user_groups_user_id_52b62117_fk_accounts_user_id'
    ) THEN
        ALTER TABLE "accounts_user_groups" 
            ADD CONSTRAINT "accounts_user_groups_user_id_52b62117_fk_accounts_user_id" 
            FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'accounts_user_groups_group_id_bd11a704_fk_auth_group_id'
    ) THEN
        ALTER TABLE "accounts_user_groups" 
            ADD CONSTRAINT "accounts_user_groups_group_id_bd11a704_fk_auth_group_id" 
            FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq'
    ) THEN
        ALTER TABLE "accounts_user_user_permissions" 
            ADD CONSTRAINT "accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq" 
            UNIQUE ("user_id", "permission_id");
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'accounts_user_user_p_user_id_e4f0a161_fk_accounts_'
    ) THEN
        ALTER TABLE "accounts_user_user_permissions" 
            ADD CONSTRAINT "accounts_user_user_p_user_id_e4f0a161_fk_accounts_" 
            FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'accounts_user_user_p_permission_id_113bb443_fk_auth_perm'
    ) THEN
        ALTER TABLE "accounts_user_user_permissions" 
            ADD CONSTRAINT "accounts_user_user_p_permission_id_113bb443_fk_auth_perm" 
            FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "accounts_user_groups_user_id_52b62117" ON "accounts_user_groups" ("user_id");
CREATE INDEX IF NOT EXISTS "accounts_user_groups_group_id_bd11a704" ON "accounts_user_groups" ("group_id");
CREATE INDEX IF NOT EXISTS "accounts_user_user_permissions_user_id_e4f0a161" ON "accounts_user_user_permissions" ("user_id");
CREATE INDEX IF NOT EXISTS "accounts_user_user_permissions_permission_id_113bb443" ON "accounts_user_user_permissions" ("permission_id");
"""

try:
    with connection.cursor() as cursor:
        # تنفيذ SQL
        cursor.execute(sql)
        print('✅ تم إنشاء جدول accounts_user في public schema')
        
        # تحديث django_migrations
        from django.db import transaction
        with transaction.atomic():
            cursor.execute("""
                INSERT INTO django_migrations (app, name, applied)
                VALUES ('accounts', '0001_initial', NOW())
                ON CONFLICT DO NOTHING
            """)
        print('✅ تم تحديث django_migrations')
        
except Exception as e:
    print(f'❌ حدث خطأ: {str(e)}')
    import traceback
    traceback.print_exc()
