# Generated by Django 5.0.14 on 2025-12-08 18:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("biological", "0003_batch_current_weight_batch_is_active_and_more"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feeding_date", models.DateField(verbose_name="تاريخ التغذية")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="كمية العلف بالكيلوجرام",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="الكمية (كجم)",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="سعر الكيلوجرام الواحد",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="سعر الوحدة",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="الكمية × سعر الوحدة",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="التكلفة الإجمالية",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feeding_logs",
                        to="biological.batch",
                        verbose_name="الدفعة",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feeding_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المسجل",
                    ),
                ),
                (
                    "feed_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feeding_logs",
                        to="inventory.feedtype",
                        verbose_name="نوع العلف",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تغذية",
                "verbose_name_plural": "سجلات التغذية",
                "ordering": ["-feeding_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["batch", "feeding_date"],
                        name="daily_opera_batch_i_6c1bda_idx",
                    ),
                    models.Index(
                        fields=["feeding_date"], name="daily_opera_feeding_523713_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MortalityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mortality_date", models.DateField(verbose_name="تاريخ النفوق")),
                (
                    "count",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="عدد النفوق",
                    ),
                ),
                (
                    "average_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="متوسط وزن السمكة النافقة",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="متوسط الوزن (كجم)",
                    ),
                ),
                (
                    "cause",
                    models.CharField(
                        blank=True,
                        help_text="سبب النفوق (مرض، نقص أكسجين، إلخ)",
                        max_length=200,
                        null=True,
                        verbose_name="سبب النفوق",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mortality_logs",
                        to="biological.batch",
                        verbose_name="الدفعة",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mortality_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المسجل",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل نفوق",
                "verbose_name_plural": "سجلات النفوق",
                "ordering": ["-mortality_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["batch", "mortality_date"],
                        name="daily_opera_batch_i_f8b415_idx",
                    ),
                    models.Index(
                        fields=["mortality_date"], name="daily_opera_mortali_86e54f_idx"
                    ),
                ],
            },
        ),
    ]
