# Generated by Django 5.0.14 on 2025-12-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_operations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedinglog",
            name="is_posted",
            field=models.BooleanField(
                default=False,
                help_text="هل تم إنشاء قيد محاسبي لهذا السجل؟",
                verbose_name="مُسجل محاسبياً",
            ),
        ),
    ]
