# Generated by Django 5.0.14 on 2025-12-09 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily_operations", "0002_add_indexes"),
        ("daily_operations", "0002_feedinglog_is_posted"),
    ]

    operations = []
