# Generated by Django 5.0.14 on 2025-12-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily_operations", "0003_merge_0002_add_indexes_0002_feedinglog_is_posted"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="feedinglog",
            name="daily_operat_batch_f_idx",
        ),
        migrations.RemoveIndex(
            model_name="feedinglog",
            name="daily_operat_feeding_idx",
        ),
        migrations.RemoveIndex(
            model_name="feedinglog",
            name="daily_operat_feed_ty_idx",
        ),
        migrations.RemoveIndex(
            model_name="mortalitylog",
            name="daily_operat_batch_m_idx",
        ),
        migrations.RemoveIndex(
            model_name="mortalitylog",
            name="daily_operat_mortalit_idx",
        ),
    ]
