# Generated by Django 5.0.14 on 2025-12-06 06:41

import django.core.validators
import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم الشركة")),
                (
                    "trade_number",
                    models.CharField(
                        blank=True,
                        help_text="رقم السجل التجاري للمؤسسة",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="رقم السجل التجاري",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="البريد الإلكتروني الرسمي للشركة",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="البريد الإلكتروني",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="رقم الهاتف الرئيسي",
                        max_length=20,
                        null=True,
                        verbose_name="الهاتف",
                    ),
                ),
                (
                    "subscription_type",
                    models.CharField(
                        choices=[
                            ("trial", "تجريبي"),
                            ("basic", "أساسي"),
                            ("professional", "احترافي"),
                            ("enterprise", "مؤسسي"),
                        ],
                        default="trial",
                        help_text="نوع باقة الاشتراك",
                        max_length=20,
                        verbose_name="نوع الاشتراك",
                    ),
                ),
                (
                    "subscription_start",
                    models.DateField(
                        auto_now_add=True, verbose_name="تاريخ بدء الاشتراك"
                    ),
                ),
                (
                    "subscription_end",
                    models.DateField(
                        blank=True,
                        help_text="تاريخ انتهاء الاشتراك (يترك فارغاً للاشتراكات الدائمة)",
                        null=True,
                        verbose_name="تاريخ انتهاء الاشتراك",
                    ),
                ),
                (
                    "on_trial",
                    models.BooleanField(
                        default=True,
                        help_text="هل العميل في فترة تجريبية؟",
                        verbose_name="في فترة تجريبية",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Soft Delete - العميل نشط أم لا",
                        verbose_name="نشط",
                    ),
                ),
                (
                    "created_on",
                    models.DateField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
            ],
            options={
                "verbose_name": "عميل",
                "verbose_name_plural": "العملاء",
                "ordering": ["-created_on"],
                "indexes": [
                    models.Index(fields=["name"], name="tenants_cli_name_57f7eb_idx"),
                    models.Index(fields=["email"], name="tenants_cli_email_0edd34_idx"),
                    models.Index(
                        fields=["is_active"], name="tenants_cli_is_acti_9a4d57_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenants.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "نطاق",
                "verbose_name_plural": "النطاقات",
            },
        ),
    ]
