# Generated by Django 5.0.14 on 2025-12-09 18:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("hatchery", "Hatchery (Starter)"),
                            ("growth", "Growth (Medium)"),
                            ("enterprise", "Enterprise (Large)"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="اسم الباقة",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="الاسم الذي يظهر للعميل",
                        max_length=100,
                        verbose_name="الاسم الظاهر",
                    ),
                ),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="السعر بالريال السعودي",
                        max_digits=10,
                        verbose_name="السعر الشهري (SAR)",
                    ),
                ),
                (
                    "price_yearly",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="السعر بالريال السعودي",
                        max_digits=10,
                        verbose_name="السعر السنوي (SAR)",
                    ),
                ),
                (
                    "max_users",
                    models.PositiveIntegerField(
                        default=2, verbose_name="الحد الأقصى للمستخدمين"
                    ),
                ),
                (
                    "max_ponds",
                    models.PositiveIntegerField(
                        default=10, verbose_name="الحد الأقصى للأحواض"
                    ),
                ),
                (
                    "max_storage_gb",
                    models.PositiveIntegerField(
                        default=1, verbose_name="الحد الأقصى للتخزين (GB)"
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        default=dict,
                        help_text="ميزات الباقة بصيغة JSON",
                        verbose_name="الميزات",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
            ],
            options={
                "verbose_name": "باقة",
                "verbose_name_plural": "الباقات",
                "ordering": ["price_monthly"],
            },
        ),
        migrations.AddField(
            model_name="client",
            name="is_active_subscription",
            field=models.BooleanField(
                default=True,
                help_text="هل الاشتراك نشط؟ (يُحدث تلقائياً)",
                verbose_name="اشتراك نشط",
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                            ("trial", "Trial"),
                        ],
                        default="trial",
                        max_length=20,
                        verbose_name="حالة الاشتراك",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="تاريخ البداية"
                    ),
                ),
                ("end_date", models.DateField(verbose_name="تاريخ الانتهاء")),
                (
                    "auto_renew",
                    models.BooleanField(
                        default=True,
                        help_text="هل يتم تجديد الاشتراك تلقائياً؟",
                        verbose_name="تجديد تلقائي",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="tenants.client",
                        verbose_name="العميل",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="tenants.plan",
                        verbose_name="الباقة",
                    ),
                ),
            ],
            options={
                "verbose_name": "اشتراك",
                "verbose_name_plural": "الاشتراكات",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "end_date"],
                        name="tenants_sub_status_c115f0_idx",
                    ),
                    models.Index(
                        fields=["client"], name="tenants_sub_client__9e4d28_idx"
                    ),
                ],
            },
        ),
    ]
