# Generated by Django 5.0.14 on 2025-12-11 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_plan_client_is_active_subscription_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم الفاتورة"
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(auto_now_add=True, verbose_name="تاريخ الفاتورة"),
                ),
                ("due_date", models.DateField(verbose_name="تاريخ الاستحقاق")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("issued", "مصدرة"),
                            ("paid", "مدفوعة"),
                            ("overdue", "متأخرة"),
                            ("cancelled", "ملغاة"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="حالة الفاتورة",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="المبلغ الفرعي"
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ضريبة القيمة المضافة",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="المبلغ الإجمالي"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="طريقة الدفع"
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الدفع"
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="مرجع الدفع"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="invoices/",
                        verbose_name="ملف PDF",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
            ],
            options={
                "verbose_name": "فاتورة اشتراك",
                "verbose_name_plural": "فواتير الاشتراكات",
                "ordering": ["-invoice_date"],
            },
        ),
        migrations.AlterModelOptions(
            name="plan",
            options={
                "ordering": ["sort_order", "price_monthly"],
                "verbose_name": "باقة",
                "verbose_name_plural": "الباقات",
            },
        ),
        migrations.RemoveIndex(
            model_name="subscription",
            name="tenants_sub_status_c115f0_idx",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="display_name",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="max_ponds",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="max_storage_gb",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="max_users",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="start_date",
        ),
        migrations.AddField(
            model_name="plan",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="وصف الباقة بالإنجليزية",
                verbose_name="الوصف",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="description_ar",
            field=models.TextField(
                blank=True,
                default="",
                help_text="وصف الباقة بالعربية",
                verbose_name="الوصف (عربي)",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="هل الباقة متاحة للاشتراك؟", verbose_name="نشط"
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="عرض كباقة مميزة في صفحة التسجيل",
                verbose_name="مميزة",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="name_ar",
            field=models.CharField(
                blank=True,
                default="",
                help_text="مثال: أساسي، احترافي، مؤسسي",
                max_length=100,
                verbose_name="اسم الباقة (عربي)",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="quotas",
            field=models.JSONField(
                default=dict,
                help_text="مثال: {'max_ponds': 10, 'max_users': 5, 'max_storage_gb': 50}",
                verbose_name="القيود",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="sort_order",
            field=models.IntegerField(
                default=0,
                help_text="ترتيب عرض الباقة في القائمة",
                verbose_name="ترتيب العرض",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="trial_days",
            field=models.IntegerField(
                default=14,
                help_text="عدد أيام التجربة المجانية",
                verbose_name="أيام التجربة",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="billing_cycle",
            field=models.CharField(
                choices=[("monthly", "شهري"), ("yearly", "سنوي")],
                default="monthly",
                max_length=10,
                verbose_name="دورة الفوترة",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الإلغاء"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="current_period_end",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="نهاية الفترة الحالية"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="current_period_start",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="بداية الفترة الحالية"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="last_payment_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ آخر دفعة"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("moyasar", "Moyasar"),
                    ("paytabs", "PayTabs"),
                ],
                default="stripe",
                max_length=50,
                verbose_name="طريقة الدفع",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="معرف العميل في Stripe"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="معرف الاشتراك في Stripe"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="total_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="إجمالي المدفوع",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="trial_ends_at",
            field=models.DateTimeField(
                blank=True,
                help_text="تاريخ انتهاء فترة التجربة",
                null=True,
                verbose_name="نهاية التجربة",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="features",
            field=models.JSONField(
                default=dict,
                help_text="مثال: {'reports': True, 'accounting': True, 'zatca': False}",
                verbose_name="الميزات",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="name",
            field=models.CharField(
                help_text="مثال: Basic, Pro, Enterprise",
                max_length=100,
                unique=True,
                verbose_name="اسم الباقة",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("trial", "تجريبي"),
                    ("active", "نشط"),
                    ("past_due", "متأخر"),
                    ("cancelled", "ملغي"),
                    ("suspended", "معلق"),
                ],
                default="trial",
                max_length=20,
                verbose_name="حالة الاشتراك",
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["status", "current_period_end"],
                name="tenants_sub_status_e67285_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["plan"], name="tenants_sub_plan_id_80483d_idx"),
        ),
        migrations.AddField(
            model_name="platforminvoice",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="tenants.subscription",
                verbose_name="الاشتراك",
            ),
        ),
        migrations.AddIndex(
            model_name="platforminvoice",
            index=models.Index(
                fields=["invoice_number"], name="tenants_pla_invoice_e43471_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="platforminvoice",
            index=models.Index(
                fields=["status", "due_date"], name="tenants_pla_status_f3f665_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="platforminvoice",
            index=models.Index(
                fields=["subscription"], name="tenants_pla_subscri_607580_idx"
            ),
        ),
    ]
