# Generated by Django 5.0.14 on 2025-12-11 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_platforminvoice_alter_plan_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "farm_name",
                    models.CharField(
                        default="", max_length=200, verbose_name="اسم المزرعة"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="بريد التواصل",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="هاتف"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, default="", verbose_name="العنوان"),
                ),
                (
                    "trade_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="السجل التجاري",
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(blank=True, default="", verbose_name="رابط الشعار"),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, default="SAR", max_length=10, verbose_name="العملة"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True,
                        default="Asia/Riyadh",
                        max_length=50,
                        verbose_name="المنطقة الزمنية",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="ملاحظات"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farm_info",
                        to="tenants.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "معلومات المزرعة",
                "verbose_name_plural": "معلومات المزارع",
            },
        ),
    ]
