# Generated by Django 5.0.14 on 2025-12-08 10:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pond",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم الحوض")),
                (
                    "pond_type",
                    models.CharField(
                        choices=[
                            ("concrete", "خرسانة"),
                            ("earth", "ترابي"),
                            ("fiberglass", "فيبرجلاس"),
                            ("cage", "قفص"),
                        ],
                        default="concrete",
                        max_length=20,
                        verbose_name="نوع الحوض",
                    ),
                ),
                (
                    "capacity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="سعة الحوض بالمتر المكعب",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="السعة (م³)",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="موقع الحوض في المزرعة",
                        max_length=200,
                        null=True,
                        verbose_name="الموقع",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "نشط"),
                            ("maintenance", "صيانة"),
                            ("empty", "فارغ"),
                            ("inactive", "غير نشط"),
                        ],
                        default="empty",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
            ],
            options={
                "verbose_name": "حوض",
                "verbose_name_plural": "الأحواض",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="الاسم العلمي")),
                (
                    "arabic_name",
                    models.CharField(max_length=200, verbose_name="الاسم العربي"),
                ),
                (
                    "scientific_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="الاسم اللاتيني",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="الوصف"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
            ],
            options={
                "verbose_name": "نوع سمكي",
                "verbose_name_plural": "الأنواع السمكية",
                "ordering": ["arabic_name"],
            },
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        help_text="رقم فريد للدفعة",
                        max_length=100,
                        unique=True,
                        verbose_name="رقم الدفعة",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البدء")),
                (
                    "initial_count",
                    models.IntegerField(
                        help_text="عدد الأسماك عند البدء",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="العدد الأولي",
                    ),
                ),
                (
                    "initial_weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="الوزن الإجمالي الأولي بالكيلوجرام",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="الوزن الأولي (كجم)",
                    ),
                ),
                (
                    "initial_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="التكلفة الأولية للزريعة",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="التكلفة الأولية",
                    ),
                ),
                (
                    "current_count",
                    models.IntegerField(
                        default=0,
                        help_text="العدد الحالي الحي",
                        verbose_name="العدد الحالي",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "نشط"),
                            ("harvested", "محصود"),
                            ("terminated", "منتهي"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "pond",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="biological.pond",
                        verbose_name="الحوض",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="biological.species",
                        verbose_name="النوع السمكي",
                    ),
                ),
            ],
            options={
                "verbose_name": "دفعة",
                "verbose_name_plural": "الدفعات",
                "ordering": ["-start_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["batch_number"], name="biological__batch_n_7119a3_idx"
                    ),
                    models.Index(
                        fields=["status"], name="biological__status_2c3258_idx"
                    ),
                    models.Index(
                        fields=["pond"], name="biological__pond_id_8052da_idx"
                    ),
                ],
            },
        ),
    ]
