# Generated by Django 5.0.14 on 2025-12-08 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biological", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LifecycleStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم المرحلة")),
                (
                    "arabic_name",
                    models.CharField(max_length=100, verbose_name="الاسم العربي"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="الوصف"),
                ),
                (
                    "min_days",
                    models.IntegerField(
                        blank=True,
                        help_text="الحد الأدنى للأيام لهذه المرحلة",
                        null=True,
                        verbose_name="الحد الأدنى للأيام",
                    ),
                ),
                (
                    "max_days",
                    models.IntegerField(
                        blank=True,
                        help_text="الحد الأقصى للأيام لهذه المرحلة",
                        null=True,
                        verbose_name="الحد الأقصى للأيام",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ترتيب المرحلة")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
            ],
            options={
                "verbose_name": "مرحلة نمو",
                "verbose_name_plural": "مراحل النمو",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="pond",
            name="coordinates_x",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="للاستخدام في الخريطة",
                max_digits=10,
                null=True,
                verbose_name="إحداثي X",
            ),
        ),
        migrations.AddField(
            model_name="pond",
            name="coordinates_y",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="للاستخدام في الخريطة",
                max_digits=10,
                null=True,
                verbose_name="إحداثي Y",
            ),
        ),
        migrations.CreateModel(
            name="FarmLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم الموقع")),
                (
                    "arabic_name",
                    models.CharField(max_length=200, verbose_name="الاسم العربي"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="الوصف"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="الموقع الأكبر (مثل: المبنى الرئيسي)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="biological.farmlocation",
                        verbose_name="الموقع الأب",
                    ),
                ),
            ],
            options={
                "verbose_name": "موقع المزرعة",
                "verbose_name_plural": "مواقع المزرعة",
                "ordering": ["arabic_name"],
            },
        ),
        migrations.AddField(
            model_name="pond",
            name="farm_location",
            field=models.ForeignKey(
                blank=True,
                help_text="الموقع الرسمي في المزرعة",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ponds",
                to="biological.farmlocation",
                verbose_name="موقع المزرعة",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="lifecycle_stages",
            field=models.ManyToManyField(
                blank=True,
                help_text="مراحل النمو لهذا النوع",
                related_name="species",
                to="biological.lifecyclestage",
                verbose_name="مراحل النمو",
            ),
        ),
    ]
