# Generated by Django 5.0.14 on 2025-12-08 18:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "biological",
            "0002_lifecyclestage_pond_coordinates_x_pond_coordinates_y_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="current_weight",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="الوزن الإجمالي الحالي بالكيلوجرام",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="الوزن الحالي (كجم)",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Soft Delete - هل الدفعة نشطة؟",
                verbose_name="نشط",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="lifecycle_stage",
            field=models.ForeignKey(
                blank=True,
                help_text="المرحلة الحالية للنمو",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="batches",
                to="biological.lifecyclestage",
                verbose_name="مرحلة النمو الحالية",
            ),
        ),
    ]
