# Generated by Django 5.0.14 on 2025-12-11 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biological", "0004_sensorreading"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="sensorreading",
            new_name="biological__pond_id_b2ad41_idx",
            old_name="biological_s_pond_i_123abc_idx",
        ),
        migrations.RenameIndex(
            model_name="sensorreading",
            new_name="biological__reading_1dee75_idx",
            old_name="biological_s_readin_idx",
        ),
        migrations.RenameIndex(
            model_name="sensorreading",
            new_name="biological__sensor__92b4b4_idx",
            old_name="biological_s_sensor_idx",
        ),
        migrations.RenameIndex(
            model_name="sensorreading",
            new_name="biological__is_aler_93bb0f_idx",
            old_name="biological_s_is_ale_idx",
        ),
        migrations.AlterField(
            model_name="sensorreading",
            name="alert_message",
            field=models.TextField(
                blank=True,
                help_text="رسالة التنبيه إذا كانت القراءة خارج النطاق الطبيعي",
                null=True,
                verbose_name="رسالة التنبيه",
            ),
        ),
        migrations.AlterField(
            model_name="sensorreading",
            name="is_alert",
            field=models.BooleanField(
                default=False,
                help_text="هل هذه القراءة تتطلب تنبيه؟ (خارج النطاق الطبيعي)",
                verbose_name="تنبيه",
            ),
        ),
        migrations.AlterField(
            model_name="sensorreading",
            name="pond",
            field=models.ForeignKey(
                help_text="الحوض الذي تم أخذ القراءة منه",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensor_readings",
                to="biological.pond",
                verbose_name="الحوض",
            ),
        ),
        migrations.AlterField(
            model_name="sensorreading",
            name="reading_date",
            field=models.DateTimeField(
                help_text="تاريخ ووقت أخذ القراءة", verbose_name="تاريخ ووقت القراءة"
            ),
        ),
        migrations.AlterField(
            model_name="sensorreading",
            name="reading_value",
            field=models.DecimalField(
                decimal_places=3,
                help_text="قيمة القراءة من المستشعر",
                max_digits=10,
                verbose_name="قيمة القراءة",
            ),
        ),
        migrations.AlterField(
            model_name="sensorreading",
            name="sensor_id",
            field=models.CharField(
                blank=True,
                help_text="معرف المستشعر في نظام IoT",
                max_length=100,
                null=True,
                verbose_name="معرف المستشعر",
            ),
        ),
        migrations.AlterField(
            model_name="sensorreading",
            name="unit",
            field=models.CharField(
                default="",
                help_text="وحدة القياس (مثل: °C، mg/L، إلخ)",
                max_length=20,
                verbose_name="الوحدة",
            ),
        ),
    ]
