# Generated by Django 5.0.14 on 2025-12-08 18:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="رقم الحساب في دليل الحسابات",
                        max_length=20,
                        unique=True,
                        verbose_name="رقم الحساب",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم الحساب")),
                (
                    "arabic_name",
                    models.CharField(max_length=200, verbose_name="الاسم العربي"),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "أصول"),
                            ("liability", "خصوم"),
                            ("equity", "حقوق ملكية"),
                            ("revenue", "إيرادات"),
                            ("expense", "مصروفات"),
                            ("biological_asset", "أصول بيولوجية"),
                        ],
                        max_length=20,
                        verbose_name="نوع الحساب",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="الوصف"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="الحساب الرئيسي (لإنشاء هيكلية شجرية)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="accounting.account",
                        verbose_name="الحساب الأب",
                    ),
                ),
            ],
            options={
                "verbose_name": "حساب",
                "verbose_name_plural": "الحسابات",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_number",
                    models.CharField(
                        help_text="رقم فريد للقيد",
                        max_length=100,
                        unique=True,
                        verbose_name="رقم القيد",
                    ),
                ),
                ("entry_date", models.DateField(verbose_name="تاريخ القيد")),
                ("description", models.TextField(verbose_name="وصف القيد")),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        help_text="مثل: feeding_log, mortality_log, harvest, sale",
                        max_length=50,
                        null=True,
                        verbose_name="نوع المرجع",
                    ),
                ),
                (
                    "reference_id",
                    models.IntegerField(
                        blank=True,
                        help_text="معرف المرجع في الجدول المصدري",
                        null=True,
                        verbose_name="رقم المرجع",
                    ),
                ),
                (
                    "is_posted",
                    models.BooleanField(
                        default=False,
                        help_text="هل تم تسجيل القيد نهائياً؟",
                        verbose_name="مُسجل",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المسجل",
                    ),
                ),
            ],
            options={
                "verbose_name": "قيد محاسبي",
                "verbose_name_plural": "القيود المحاسبية",
                "ordering": ["-entry_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntryLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("debit", "مدين"), ("credit", "دائن")],
                        help_text="مدين أو دائن",
                        max_length=10,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="المبلغ",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="وصف البند"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_entry_lines",
                        to="accounting.account",
                        verbose_name="الحساب",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="accounting.journalentry",
                        verbose_name="القيد المحاسبي",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند قيد محاسبي",
                "verbose_name_plural": "بنود القيود المحاسبية",
                "ordering": ["journal_entry", "type", "account"],
            },
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["code"], name="accounting__code_c93a8f_idx"),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["account_type"], name="accounting__account_889d6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["entry_number"], name="accounting__entry_n_734b5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["entry_date"], name="accounting__entry_d_79c286_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["reference_type", "reference_id"],
                name="accounting__referen_4bf694_idx",
            ),
        ),
    ]
