# Generated by Django 5.0.14 on 2025-12-11 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_add_indexes"),
        ("biological", "0003_batch_current_weight_batch_is_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BiologicalAssetRevaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revaluation_date",
                    models.DateField(verbose_name="تاريخ إعادة التقييم"),
                ),
                (
                    "carrying_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="القيمة المسجلة في الحسابات قبل إعادة التقييم",
                        max_digits=15,
                        verbose_name="القيمة الدفترية",
                    ),
                ),
                (
                    "fair_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="الوزن الحالي × سعر السوق",
                        max_digits=15,
                        verbose_name="القيمة العادلة",
                    ),
                ),
                (
                    "market_price_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="سعر السوق الحالي للكيلوجرام",
                        max_digits=10,
                        verbose_name="سعر السوق (ريال/كجم)",
                    ),
                ),
                (
                    "current_weight_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="الوزن التقديري الحالي للدفعة",
                        max_digits=12,
                        verbose_name="الوزن الحالي (كجم)",
                    ),
                ),
                (
                    "current_count",
                    models.IntegerField(
                        help_text="عدد الأسماك الحالي في الدفعة",
                        verbose_name="العدد الحالي",
                    ),
                ),
                (
                    "unrealized_gain_loss",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="الفرق بين القيمة العادلة والقيمة الدفترية",
                        max_digits=15,
                        verbose_name="ربح/خسارة غير محققة",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "إعادة تقييم أصل بيولوجي",
                "verbose_name_plural": "إعادة تقييم الأصول البيولوجية",
                "ordering": ["-revaluation_date", "-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="journalentryline",
            options={
                "ordering": ["journal_entry", "type", "id"],
                "verbose_name": "بند قيد",
                "verbose_name_plural": "بنود القيود",
            },
        ),
        migrations.RemoveIndex(
            model_name="account",
            name="accounting_a_account__idx",
        ),
        migrations.RemoveIndex(
            model_name="journalentry",
            name="accounting_j_entry_d_7a8f1d_idx",
        ),
        migrations.RemoveIndex(
            model_name="journalentry",
            name="accounting_j_referen_idx",
        ),
        migrations.RemoveIndex(
            model_name="journalentryline",
            name="accounting_j_account_idx",
        ),
        migrations.RemoveIndex(
            model_name="journalentryline",
            name="accounting_j_journal__idx",
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="entry_number",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="رقم القيد"
            ),
        ),
        migrations.AlterField(
            model_name="journalentryline",
            name="type",
            field=models.CharField(
                choices=[("debit", "مدين"), ("credit", "دائن")],
                max_length=10,
                verbose_name="نوع البند",
            ),
        ),
        migrations.AddField(
            model_name="biologicalassetrevaluation",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revaluations",
                to="biological.batch",
                verbose_name="الدفعة",
            ),
        ),
        migrations.AddField(
            model_name="biologicalassetrevaluation",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="المُنشئ",
            ),
        ),
        migrations.AddField(
            model_name="biologicalassetrevaluation",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="biological_revaluations",
                to="accounting.journalentry",
                verbose_name="القيد المحاسبي",
            ),
        ),
        migrations.AddIndex(
            model_name="biologicalassetrevaluation",
            index=models.Index(
                fields=["batch", "revaluation_date"],
                name="accounting__batch_i_10f8bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="biologicalassetrevaluation",
            index=models.Index(
                fields=["revaluation_date"], name="accounting__revalua_a982f6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="biologicalassetrevaluation",
            unique_together={("batch", "revaluation_date")},
        ),
    ]
