# Generated by Django 5.0.14 on 2025-12-08 19:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("biological", "0003_batch_current_weight_batch_is_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Harvest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("harvest_date", models.DateField(verbose_name="تاريخ الحصاد")),
                (
                    "quantity_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="كمية السمك المحصود بالكيلوجرام",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="الكمية (كجم)",
                    ),
                ),
                (
                    "count",
                    models.IntegerField(
                        help_text="عدد الأسماك المحصودة",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="العدد",
                    ),
                ),
                (
                    "average_weight",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="متوسط الوزن (كجم)",
                    ),
                ),
                (
                    "fair_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="القيمة العادلة للسمك المحصود",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="القيمة العادلة",
                    ),
                ),
                (
                    "cost_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="التكلفة التراكمية لكل كيلوجرام",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="التكلفة لكل كيلوجرام",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("in_progress", "قيد التنفيذ"),
                            ("completed", "مكتمل"),
                            ("cancelled", "ملغي"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="harvests",
                        to="biological.batch",
                        verbose_name="الدفعة",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="harvests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المسجل",
                    ),
                ),
            ],
            options={
                "verbose_name": "حصاد",
                "verbose_name_plural": "الحصاد",
                "ordering": ["-harvest_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        help_text="رقم فريد لطلب البيع",
                        max_length=100,
                        unique=True,
                        verbose_name="رقم الطلب",
                    ),
                ),
                ("order_date", models.DateField(verbose_name="تاريخ الطلب")),
                (
                    "customer_name",
                    models.CharField(max_length=200, verbose_name="اسم العميل"),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="هاتف العميل"
                    ),
                ),
                (
                    "customer_address",
                    models.TextField(
                        blank=True, null=True, verbose_name="عنوان العميل"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="المجموع الفرعي",
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15.00"),
                        help_text="معدل ضريبة القيمة المضافة",
                        max_digits=5,
                        verbose_name="معدل الضريبة (%)",
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="مبلغ الضريبة",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="المبلغ الإجمالي",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("confirmed", "مؤكد"),
                            ("invoiced", "مفوتر"),
                            ("delivered", "تم التسليم"),
                            ("cancelled", "ملغي"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المسجل",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب بيع",
                "verbose_name_plural": "طلبات البيع",
                "ordering": ["-order_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="رقم الفاتورة الضريبية",
                        max_length=100,
                        unique=True,
                        verbose_name="رقم الفاتورة",
                    ),
                ),
                ("invoice_date", models.DateField(verbose_name="تاريخ الفاتورة")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="المجموع الفرعي"
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="مبلغ الضريبة"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="المبلغ الإجمالي"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("issued", "مصدرة"),
                            ("paid", "مدفوعة"),
                            ("cancelled", "ملغاة"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "qr_code",
                    models.TextField(blank=True, null=True, verbose_name="QR Code"),
                ),
                (
                    "uuid",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="UUID"
                    ),
                ),
                (
                    "signed_xml",
                    models.TextField(blank=True, null=True, verbose_name="XML الموقع"),
                ),
                (
                    "zatca_status",
                    models.CharField(
                        blank=True,
                        help_text="حالة إرسال الفاتورة إلى ZATCA",
                        max_length=50,
                        null=True,
                        verbose_name="حالة ZATCA",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المسجل",
                    ),
                ),
                (
                    "sales_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice",
                        to="sales.salesorder",
                        verbose_name="طلب البيع",
                    ),
                ),
            ],
            options={
                "verbose_name": "فاتورة",
                "verbose_name_plural": "الفواتير",
                "ordering": ["-invoice_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_kg",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="الكمية (كجم)",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="سعر الكيلوجرام",
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="المجموع",
                    ),
                ),
                (
                    "harvest",
                    models.ForeignKey(
                        help_text="السمك المباع من هذا الحصاد",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_order_lines",
                        to="sales.harvest",
                        verbose_name="الحصاد",
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.salesorder",
                        verbose_name="طلب البيع",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند طلب بيع",
                "verbose_name_plural": "بنود طلبات البيع",
                "ordering": ["sales_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="harvest",
            index=models.Index(
                fields=["batch", "harvest_date"], name="sales_harve_batch_i_c50de4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="harvest",
            index=models.Index(fields=["status"], name="sales_harve_status_139aef_idx"),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(
                fields=["order_number"], name="sales_sales_order_n_78c57a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(fields=["status"], name="sales_sales_status_480214_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_number"], name="sales_invoi_invoice_51f3c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="sales_invoi_status_4e3758_idx"),
        ),
    ]
