# Generated by Django 5.0.14 on 2025-12-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_add_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="harvest",
            name="sales_harves_batch_h_idx",
        ),
        migrations.RemoveIndex(
            model_name="harvest",
            name="sales_harves_harvest_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="sales_invoi_invoice_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="sales_invoi_invoice_n_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="sales_invoi_sales_o_idx",
        ),
        migrations.RemoveIndex(
            model_name="salesorder",
            name="sales_saleso_order_d_idx",
        ),
        migrations.RemoveIndex(
            model_name="salesorder",
            name="sales_saleso_order_n_idx",
        ),
    ]
