# Generated by Django 5.0.14 on 2025-12-11 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_remove_harvest_sales_harves_batch_h_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="salesorderline",
            name="sales_saleso_sales_o_idx",
        ),
        migrations.RemoveIndex(
            model_name="salesorderline",
            name="sales_saleso_harvest_idx",
        ),
    ]
